### ISSUE TITLE
tsc command not working on Windows

### ISSUE THREAD

**Issue by Dahlgren** [gruppe-adler/arma3-serverinfo#3]
`npm install` containing

```
./node_modules/tsd/build/cli.js reinstall --save --override; node_modules/typescript/bin/tsc --module commonjs  ./*.ts */*.ts
```

triggers the following error on Windows,
`'.' is not recognized as an internal or external command, operable program or batch file.`

**Comment by Fusselwurm** [comment]
goddamnit. 

Separate build scripts for windows/linux then? Whats the Right Way(tm) to do it?

**Comment by Dahlgren** [comment]
Using gulp would probably be a good solution
- https://www.npmjs.com/package/gulp-tsd
- https://www.npmjs.com/package/gulp-tsc

I can do a PR with the required changes and test it on Linux & Windows

**Comment by Fusselwurm** [comment]
:+1:
